name: Satellite Network CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show Files
        run: ls -la

      - name: Create Build Report
        run: echo "GitHub Actions CI build successful" > github-build-report.txt

      - name: Upload Build Report
        uses: actions/upload-artifact@v4
        with:
          name: github-build-report
          path: github-build-report.txt